version: "3.8"

services:
  sudoku:
    build:
      context: ./src
    ports:
      - "9090:8080" 
    working_dir: /app/python
    environment:
      - PORT=8080
      - FLASK_ENV=development
    command: >
      sh -c "cd /app/c && make && cd /app/python && python server.py"
