version: "3.8"

services:
  sudoku:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
     - "9090:8080"
    volumes:
      - ./src/python:/app 
      - ./src/c:/app/c    
      - ./src/assets:/app/assets
    environment:
      - DOCKER_ENV=1
      - PORT=8080
      - FLASK_ENV=development
    command: >
      sh -c "cd /app/c && make && cd /app && python server.py"
