# Pipeline do GitHub Actions

name: CI/CD for Sudoku Validator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: sudo apt update && sudo apt install -y gcc make python3-tk

      - name: Compilar o código C
        run: |
          cd src/c
          make

      - name: Testar Sudoku Validator
        run: |
          cd src/c
          ./sudoku_validator

      - name: Configurar Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t georgianagraca/sudoku-validator .
          docker push georgianagraca/sudoku-validator


      - name: Atualizar Servidor
        run: |
          ssh usuario@<SEU_SERVIDOR> "docker pull georgianagraca/sudoku-validator && docker run --rm georgianagraca/sudoku-validator"
